### ISSUE TITLE
Restrict file size on resume to 20mb

### ISSUE THREAD

**Issue by APherwani** [KnightHacks/hackathon-2021-backend#76]
There is no upper limit to the file size for resumes. This allows malicious actors potentially try a DoS attack by completely filling up our storage. Introducing a file limit on the server side will keep our service running properly.

Upload a huge file for your resume.

----

If there is a file uploaded above 20mb we can go ahead and throw a bad request. I don't think any resume will be larger than that and if the user attempts to upload anything larger they're probably malicious.

**Comment by TorrentofShame** [comment]
Resolved in v2.1.1
